# Here you can write your custom setting for python formatting.
# Lib - https://github.com/google/yapf
# List of all rules - https://github.com/google/yapf#knobs
[tool.yapf]
based_on_style = "yapf"
indent_width = "4"
BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = "false"
COLUMN_LIMIT = "120" # max line-length

[tool.yapfignore]
ignore_patterns = [
  "example/**/*.py"
]

[tool.isort]
line_length = "120" # max line-length

[tool.ruff]
line-length = 120

# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
[tool.pyright]
typeCheckingMode = "basic"
include = ["src"]
exclude = ["tests"]
ignore = ["**/node_modules"]
pythonVersion = "3.10.11"
pythonPlatform = "Windows"
reportMissingImports = true
venvPath = "."
venv = "venv"
