# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#MOSCOW
DEFAULT_EVENT_TIME_ZONE = "Europe/Moscow"
DEFAULT_EVENT_SCHEDULED_TIME = 1000

# TODO: Добавить дефолтный меседж для тост уведомлений, на каждый ивент свое сообщение, что на этом ивенте ты можешь получить и количество ну и шуточка)
DEFAULT_EVENTS = {
    "HAPPY_HOUR": {
        "tech_name": "HAPPY_HOUR",
        "name": "Счастливые Полчаса (+10%)",
        "times": ["01:00", "04:00", "05:30", "07:00", "09:00", "12:00", "14:30", "17:30", "19:00", "22:00"],
        "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "win": 3,
        "los": 1,
        "msg": "",
    },
    "MAJESTIC_TVT": {
        "tech_name": "MAJESTIC_TVT",
        "name": "Majestic TvT",
        "times": ["09:50", "12:50", "17:50"],
        "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "win": 3,
        "los": 1,
        "msg": "",
    },
    "IMPERIAL_TVT": {
        "tech_name": "IMPERIAL_TVT",
        "name": "Imperial TvT",
        "times": ["02:30", "04:30", "15:30", "20:30", "22:30"],
        "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "win": 3,
        "los": 1,
        "msg": "",
    },
    "ROYAL_TVT": {
        "tech_name": "ROYAL_TVT",
        "name": "Royal TvT",
        "times": ["19:30", "21:30", "23:30"],
        "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "win": 3,
        "los": 1,
        "msg": "",
    },
    "LAST_HERO": {
        "tech_name": "LAST_HERO",
        "name": "Последний Герой",
        "times": ["12:30", "18:30"],
        "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "win": 3,
        "los": 1,
        "msg": "Ну... Могу лишь сказать что гарантировано ты получишь пизды и собственно это все что тебе светит на этом ивенте.",
    },
    "MEAT_GRINDER": {
        "tech_name": "MEAT_GRINDER",
        "name": "Мясорубка",
        "times": ["07:50", "11:50", "19:50", "23:50"],
        "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "win": 3,
        "los": 1,
        "msg": "",
    },
    "ELPY_INVASION": {
        "tech_name": "ELPY_INVASION",
        "name": "Нашествие Эльпи",
        "times": ["02:20", "05:20", "10:20", "13:20", "17:20", "19:20", "21:20", "23:20"],
        "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "win": 3,
        "los": 1,
        "msg": "",
    },
    "TOVUS_TREASURE": {
        "tech_name": "TOVUS_TREASURE",
        "name": "Сокровище Тову",
        "times": ["00:20", "03:20", "07:20", "11:20", "14:20", "16:20", "20:20", "22:20"],
        "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "win": 3,
        "los": 1,
        "msg": "",
    },
    "ALLIANCE_BASE_SIEGE": {
        "tech_name": "ALLIANCE_BASE_SIEGE",
        "name": "Осада Базы Альянса",
        "times": ["19:00"],
        "days": ["Wednesday", "Saturday"],
        "win": 3,
        "los": 1,
        "msg": "",
    },
    "CHAOS_FESTIVAL": {
        "tech_name": "CHAOS_FESTIVAL",
        "name": "Фестиваль Хаоса",
        "times": [
            "20:00",
            "20:15",
            "20:25",
            "20:35",
            "21:00",
            "21:15",
            "21:25",
            "21:35",
            "22:00",
            "22:15",
            "22:25",
            "22:35",
            "23:00",
            "23:15",
            "23:25",
            "23:35",
        ],
        "days": ["Monday", "Tuesday", "Wednesday", "Thursday"],
        "win": 3,
        "los": 1,
        "msg": "",
    },
    "TEST_DATA": {
        "tech_name": "TEST_DATA",
        "name": "Тестовый",
        "times": ["22:49", "22:51"],
        "days": ["Friday", "Saturday", "Sunday"],
        "win": 3,
        "los": 1,
        "msg": "",
    },
}
